### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by bedna-KU** [gtsoukas/scene_text#2]
pip install scene_text
...
...
...
Collecting torch==0.3.1 (from scene_text)
  ERROR: Could not find a version that satisfies the requirement torch==0.3.1 (from scene_text) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 0.4.1, 0.4.1.post2, 1.0.0, 1.0.1, 1.0.1.post2, 1.1.0, 1.2.0, 1.3.0, 1.3.1)
ERROR: No matching distribution found for torch==0.3.1 (from scene_text)

**Comment by gtsoukas** [comment]
@bedna-KU could you give some details on your environment? When I run pip install from Docker image python:3.6-stretch it installs properly.
```
docker run --rm -i -t  python:3.6-stretch /bin/bash
pip install scene-text
python -c "import scene_text; print(scene_text.__version__)"
# produces: *0.2.2* 
```
Also note, I am using *-* instead of *_* in the pip install command.

**Comment by bedna-KU** [comment]
I use antiX Linux (like Debian without systemd).

python3 -V
Python 3.7.5

pip -V
pip 18.1 from /home/mario/DevFinal/text_reader/env/lib/python3.7/site-packages/pip (python 3.7)

**Comment by gtsoukas** [comment]
Sorry, this currently only works with Python 3.6 but not 3.7.
